/*
 * stepper_config.h
 *
 *  Created on: 06.03.2026
 *      Author: roman
 */

#ifndef MOTOR_STEPPER_CONFIG_H_
#define MOTOR_STEPPER_CONFIG_H_


#define ENABLE_STEP			1
#define ENABLE_DIR			1
#define ENABLE_EN			1
#define ENABLE_ROT			0
#define OVERFLOW_HANDLING	1

//Direction
#define FWD	(true)
#define REV	(false)


#define ENABLE_MIN_DELAY_TIME_MS	400		//Wait x MS after setting Enable for the next action
#define DIR_MIN_DELAY_TIME_MS		1		//Wait x MS after setting Direction for the next action
											// See Driver Manual vor Minimum Values

#if ENABLE_STEP
#define MOTOR1_TIMER_CHNL			1
#define MOTOR1_STEP      			(PORTA->PCR[4])
#define MOTOR1_STEP_GPIO()     		(MOTOR1_STEP = PORT_PCR_MUX(1)|PORT_PCR_PS(0)|PORT_PCR_PE(1)|PORT_PCR_DSE(1))
#define MOTOR1_STEP_FTM()      		(MOTOR1_STEP = PORT_PCR_MUX(3)|PORT_PCR_PS(1)|PORT_PCR_PE(1)|PORT_PCR_DSE(1))
#define MOTOR1_STEP_GPIO_OUTPUT()  	(GPIOA->PDDR|=(1<<4))
#define MOTOR1_STEP_GPIO_LOW()  	(GPIOA->PCOR=(1<<4))
#define MOTOR1_STEP_GPIO_HIGH() 	(GPIOA->PSOR=(1<<4))
#define MOTOR1_STEP_STATUS() 		(GPIOA->PDOR&(1<<4))

#define MOTOR2_TIMER_CHNL			2
#define MOTOR2_STEP      			(PORTA->PCR[5])
#define MOTOR2_STEP_GPIO()     		(MOTOR2_STEP = PORT_PCR_MUX(1)|PORT_PCR_PS(0)|PORT_PCR_PE(1)|PORT_PCR_DSE(1))
#define MOTOR2_STEP_FTM()      		(MOTOR2_STEP = PORT_PCR_MUX(3)|PORT_PCR_PS(1)|PORT_PCR_PE(1)|PORT_PCR_DSE(1))
#define MOTOR2_STEP_GPIO_OUTPUT()  	(GPIOA->PDDR|=(1<<5))
#define MOTOR2_STEP_GPIO_LOW()  	(GPIOA->PCOR=(1<<5))
#define MOTOR2_STEP_GPIO_HIGH() 	(GPIOA->PSOR=(1<<5))
#define MOTOR2_STEP_STATUS() 		(GPIOA->PDOR&(1<<5))

#define MOTOR3_TIMER_CHNL			4
#define MOTOR3_STEP      			(PORTD->PCR[4])
#define MOTOR3_STEP_GPIO()     		(MOTOR3_STEP = PORT_PCR_MUX(1)|PORT_PCR_PS(0)|PORT_PCR_PE(1)|PORT_PCR_DSE(1))
#define MOTOR3_STEP_FTM()      		(MOTOR3_STEP = PORT_PCR_MUX(4)|PORT_PCR_PS(1)|PORT_PCR_PE(1)|PORT_PCR_DSE(1))
#define MOTOR3_STEP_GPIO_OUTPUT()  	(GPIOD->PDDR|=(1<<4))
#define MOTOR3_STEP_GPIO_LOW()  	(GPIOD->PCOR=(1<<4))
#define MOTOR3_STEP_GPIO_HIGH() 	(GPIOD->PSOR=(1<<4))
#define MOTOR3_STEP_STATUS() 		(GPIOD->PDOR&(1<<4))

#define MOTORROT_TIMER_CHNL			5
#define MOTOROT_STEP      			(PORTD->PCR[5])
#define MOTORROT_STEP_GPIO()    	(MOTOROT_STEP = PORT_PCR_MUX(1)|PORT_PCR_PS(0)|PORT_PCR_PE(1)|PORT_PCR_DSE(1))
#define MOTORROT_STEP_FTM()     	(MOTOROT_STEP |= PORT_PCR_MUX(4))
#define MOTORROT_STEP_GPIO_OUTPUT()	(GPIOD->PDDR|=(1<<5))
#define MOTORROT_STEP_GPIO_LOW()  	(GPIOD->PCOR=(1<<5))
#define MOTORROT_STEP_GPIO_HIGH() 	(GPIOD->PSOR=(1<<5))
#define MOTORROT_STEP_STATUS()	 	(GPIOD->PDOR&(1<<5))
#endif

#if ENABLE_DIR					// Achtung Alle GPIO Bezogen auf PortB (statisch)
#define MOTOR1_DIR_PORT      	PORTB
#define MOTOR1_DIR_REG      	(0)
#define MOTOR1_DIR_GPIO()     	((MOTOR1_DIR_PORT) ->PCR[MOTOR1_DIR_REG] = PORT_PCR_MUX(1)|PORT_PCR_PS(0)|PORT_PCR_PE(1)|PORT_PCR_DSE(1))
#define MOTOR1_DIR_FWD()     	(GPIOB->PSOR=(1<<MOTOR1_DIR_REG))
#define MOTOR1_DIR_REV()     	(GPIOB->PCOR=(1<<MOTOR1_DIR_REG))

#define MOTOR2_DIR_PORT      	PORTB
#define MOTOR2_DIR_REG      	(1)
#define MOTOR2_DIR_GPIO()     	((MOTOR2_DIR_PORT) ->PCR[MOTOR2_DIR_REG] = PORT_PCR_MUX(1)|PORT_PCR_PS(0)|PORT_PCR_PE(1)|PORT_PCR_DSE(1))
#define MOTOR2_DIR_FWD()     	(GPIOB->PSOR=(1<<MOTOR2_DIR_REG))
#define MOTOR2_DIR_REV()     	(GPIOB->PCOR=(1<<MOTOR2_DIR_REG))

#define MOTOR3_DIR_PORT      	PORTB
#define MOTOR3_DIR_REG      	(2)
#define MOTOR3_DIR_GPIO()     	((MOTOR3_DIR_PORT) ->PCR[MOTOR3_DIR_REG] = PORT_PCR_MUX(1)|PORT_PCR_PS(0)|PORT_PCR_PE(1)|PORT_PCR_DSE(1))
#define MOTOR3_DIR_FWD()     	(GPIOB->PSOR=(1<<MOTOR3_DIR_REG))
#define MOTOR3_DIR_REV()     	(GPIOB->PCOR=(1<<MOTOR3_DIR_REG))

#define MOTORROT_DIR_PORT      	PORTB
#define MOTORROT_DIR_REG      	(3)
#define MOTORROT_DIR_GPIO()     ((MOTORROT_DIR_PORT) ->PCR[MOTORROT_DIR_REG] = PORT_PCR_MUX(1)|PORT_PCR_PS(0)|PORT_PCR_PE(1)|PORT_PCR_DSE(1))
#define MOTORROT_DIR_FWD()     	(GPIOB->PSOR=(1<<MOTORROT_DIR_REG))
#define MOTORROT_DIR_REV()     	(GPIOB->PCOR=(1<<MOTORROT_DIR_REG))

#define MOTOR_DIR_OUTPUT()		(GPIOB->PDDR |=(1<<MOTOR1_DIR_REG)|(1<<MOTOR2_DIR_REG)|(1<<MOTOR3_DIR_REG)|(1<<MOTORROT_DIR_REG))
#endif


#if ENABLE_EN

#define MOTOR1_EN_PORT      	PORTB
#define MOTOR1_EN_REG      		(16)
#define MOTOR1_EN_GPIO()     	((MOTOR1_EN_PORT) ->PCR[MOTOR1_EN_REG] = PORT_PCR_MUX(1)| PORT_PCR_PS(0)|PORT_PCR_PE(1)|PORT_PCR_DSE(1))
#define MOTOR1_EN_ENABLE()     	(GPIOB->PSOR=(1<<MOTOR1_EN_REG))
#define MOTOR1_EN_DISABLE()     (GPIOB->PCOR=(1<<MOTOR1_EN_REG))

#define MOTOR2_EN_PORT      	PORTB
#define MOTOR2_EN_REG      		(17)
#define MOTOR2_EN_GPIO()     	((MOTOR2_EN_PORT) ->PCR[MOTOR2_EN_REG] = PORT_PCR_MUX(1)|PORT_PCR_PS(0)|PORT_PCR_PE(1)|PORT_PCR_DSE(1))
#define MOTOR2_EN_ENABLE()     	(GPIOB->PSOR=(1<<MOTOR2_EN_REG))
#define MOTOR2_EN_DISABLE()    	(GPIOB->PCOR=(1<<MOTOR2_EN_REG))

#define MOTOR3_EN_PORT      	PORTB
#define MOTOR3_EN_REG      		(18)
#define MOTOR3_EN_GPIO()     	((MOTOR3_EN_PORT) ->PCR[MOTOR3_EN_REG] = PORT_PCR_MUX(1)|PORT_PCR_PS(0)|PORT_PCR_PE(1)|PORT_PCR_DSE(1))
#define MOTOR3_EN_ENABLE()     	(GPIOB->PSOR=(1<<MOTOR3_EN_REG))
#define MOTOR3_EN_DISABLE()    	(GPIOB->PCOR=(1<<MOTOR3_EN_REG))

#define MOTORROT_EN_PORT      	PORTB
#define MOTORROT_EN_REG      	(19)
#define MOTORROT_EN_GPIO()     	((MOTORROT_EN_PORT) ->PCR[MOTORROT_EN_REG] = PORT_PCR_MUX(1)|PORT_PCR_PS(0)|PORT_PCR_PE(1)|PORT_PCR_DSE(1))
#define MOTORROT_EN_ENABLE()    (GPIOB->PSOR=(1<<MOTORROT_EN_REG))
#define MOTORROT_EN_DISABLE()   (GPIOB->PCOR=(1<<MOTORROT_EN_REG))

#define MOTOR_EN_OUTPUT()		(GPIOB->PDDR |=(1<<MOTOR1_EN_REG)|(1<<MOTOR2_EN_REG)|(1<<MOTOR3_EN_REG)|(1<<MOTORROT_EN_REG))
#endif

#endif /* MOTOR_STEPPER_CONFIG_H_ */
