/*
 * stepper_config.h
 *
 *  Created on: 06.03.2026
 *      Author: roman
 */

#ifndef MOTOR_STEPPER_CONFIG_H_
#define MOTOR_STEPPER_CONFIG_H_


#define ENABLE_STEP			1
#define ENABLE_DIR			1
#define ENABLE_EN			1
#define ENABLE_ROT			1
#define OVERFLOW_HANDLING	1

// Definition Direction
#define FWD	(true)
#define REV	(false)


#define ENABLE_MIN_DELAY_TIME_MS	400		// Wait x MS after setting Enable for the next action
#define DIR_MIN_DELAY_TIME_MS		1		// Wait x MS after setting Direction for the next action
											// See Driver Manual vor Minimum Values

#undef PORT

// Common Definitions
#define _PORT_MKR(x)   PORT##x
#define PORT_MKR(x)    _PORT_MKR(x)
#define _GPIO_MKR(x)   GPIO##x
#define GPIO_MKR(x)    _GPIO_MKR(x)

#if ENABLE_STEP

#define MOTOR1_STEP_TIMER_CHNL			1		// USR Config
#define MOTOR1_STEP_PORT				A		// USR Config
#define MOTOR1_STEP_REG					4		// USR Config
#define MOTOR1_STEP_PULL_ENABLE			(1) 	// USR Config		// 1 = Enable, 0 = Disable
#define MOTOR1_STEP_PULLUP				(0) 	// USR Config		// 1 = Pullup, 0 = Pulldown
#define MOTOR1_STEP_DSE					(1) 	// USR Config		// 1 = Drive Strength enable , 0 = off
#define MOTOR1_STEP_PORT_NAME 			PORT_MKR(MOTOR1_STEP_PORT)
#define MOTOR1_STEP_GPIO_NAME 			GPIO_MKR(MOTOR1_STEP_PORT)
#define MOTOR1_STEP_MUX_GPIO()     		(MOTOR1_STEP_PORT_NAME->PCR[MOTOR1_STEP_REG]= PORT_PCR_MUX(1)|PORT_PCR_PS(MOTOR1_STEP_PULLUP)|PORT_PCR_PE(MOTOR1_STEP_PULL_ENABLE)|PORT_PCR_DSE(MOTOR1_STEP_DSE))
#define MOTOR1_STEP_MUX_FTM()     		(MOTOR1_STEP_PORT_NAME->PCR[MOTOR1_STEP_REG]= PORT_PCR_MUX(3)|PORT_PCR_PS(MOTOR1_STEP_PULLUP)|PORT_PCR_PE(MOTOR1_STEP_PULL_ENABLE)|PORT_PCR_DSE(MOTOR1_STEP_DSE))
#define MOTOR1_STEP_SET_OUTPUT()  		(MOTOR1_STEP_GPIO_NAME->PDDR|=(1<<MOTOR1_STEP_REG))
#define MOTOR1_STEP_GPIO_LOW()  		(MOTOR1_STEP_GPIO_NAME->PCOR=(1<<MOTOR1_STEP_REG))
#define MOTOR1_STEP_GPIO_HIGH() 		(MOTOR1_STEP_GPIO_NAME->PSOR=(1<<MOTOR1_STEP_REG))
#define MOTOR1_STEP_GPIO_TOGGLE() 		(MOTOR1_STEP_GPIO_NAME->PTOR=(1<<MOTOR1_STEP_REG))
#define MOTOR1_STEP_STATUS() 			(MOTOR1_STEP_GPIO_NAME->PDOR&(1<<MOTOR1_STEP_REG))

#define MOTOR2_STEP_TIMER_CHNL			2		// USR Config
#define MOTOR2_STEP_PORT				A		// USR Config
#define MOTOR2_STEP_REG					5		// USR Config
#define MOTOR2_STEP_PULL_ENABLE			(1) 	// USR Config		// 1 = Enable, 0 = Disable
#define MOTOR2_STEP_PULLUP				(0) 	// USR Config		// 1 = Pullup, 0 = Pulldown
#define MOTOR2_STEP_DSE					(1) 	// USR Config		// 1 = Drive Strength enable , 0 = off
#define MOTOR2_STEP_PORT_NAME 			PORT_MKR(MOTOR2_STEP_PORT)
#define MOTOR2_STEP_GPIO_NAME 			GPIO_MKR(MOTOR2_STEP_PORT)
#define MOTOR2_STEP_MUX_GPIO()     		(MOTOR2_STEP_PORT_NAME->PCR[MOTOR2_STEP_REG]= PORT_PCR_MUX(1)|PORT_PCR_PS(MOTOR2_STEP_PULLUP)|PORT_PCR_PE(MOTOR2_STEP_PULL_ENABLE)|PORT_PCR_DSE(MOTOR2_STEP_DSE))
#define MOTOR2_STEP_MUX_FTM()     		(MOTOR2_STEP_PORT_NAME->PCR[MOTOR2_STEP_REG]= PORT_PCR_MUX(3)|PORT_PCR_PS(MOTOR2_STEP_PULLUP)|PORT_PCR_PE(MOTOR2_STEP_PULL_ENABLE)|PORT_PCR_DSE(MOTOR2_STEP_DSE))
#define MOTOR2_STEP_SET_OUTPUT()  		(MOTOR2_STEP_GPIO_NAME->PDDR|=(1<<MOTOR2_STEP_REG))
#define MOTOR2_STEP_GPIO_LOW()  		(MOTOR2_STEP_GPIO_NAME->PCOR=(1<<MOTOR2_STEP_REG))
#define MOTOR2_STEP_GPIO_HIGH() 		(MOTOR2_STEP_GPIO_NAME->PSOR=(1<<MOTOR2_STEP_REG))
#define MOTOR2_STEP_GPIO_TOGGLE() 		(MOTOR2_STEP_GPIO_NAME->PTOR=(1<<MOTOR2_STEP_REG))
#define MOTOR2_STEP_STATUS() 			(MOTOR2_STEP_GPIO_NAME->PDOR&(1<<MOTOR2_STEP_REG))

#define MOTOR3_STEP_TIMER_CHNL			4		// USR Config
#define MOTOR3_STEP_PORT				D		// USR Config
#define MOTOR3_STEP_REG					4		// USR Config
#define MOTOR3_STEP_PULL_ENABLE			(1) 	// USR Config		// 1 = Enable, 0 = Disable
#define MOTOR3_STEP_PULLUP				(0) 	// USR Config		// 1 = Pullup, 0 = Pulldown
#define MOTOR3_STEP_DSE					(1) 	// USR Config		// 1 = Drive Strength enable , 0 = off
#define MOTOR3_STEP_PORT_NAME 			PORT_MKR(MOTOR3_STEP_PORT)
#define MOTOR3_STEP_GPIO_NAME 			GPIO_MKR(MOTOR3_STEP_PORT)
#define MOTOR3_STEP_MUX_GPIO()     		(MOTOR3_STEP_PORT_NAME->PCR[MOTOR3_STEP_REG]= PORT_PCR_MUX(1)|PORT_PCR_PS(MOTOR3_STEP_PULLUP)|PORT_PCR_PE(MOTOR3_STEP_PULL_ENABLE)|PORT_PCR_DSE(MOTOR3_STEP_DSE))
#define MOTOR3_STEP_MUX_FTM()     		(MOTOR3_STEP_PORT_NAME->PCR[MOTOR3_STEP_REG]= PORT_PCR_MUX(3)|PORT_PCR_PS(MOTOR3_STEP_PULLUP)|PORT_PCR_PE(MOTOR3_STEP_PULL_ENABLE)|PORT_PCR_DSE(MOTOR3_STEP_DSE))
#define MOTOR3_STEP_SET_OUTPUT()  		(MOTOR3_STEP_GPIO_NAME->PDDR|=(1<<MOTOR3_STEP_REG))
#define MOTOR3_STEP_GPIO_LOW()  		(MOTOR3_STEP_GPIO_NAME->PCOR=(1<<MOTOR3_STEP_REG))
#define MOTOR3_STEP_GPIO_HIGH() 		(MOTOR3_STEP_GPIO_NAME->PSOR=(1<<MOTOR3_STEP_REG))
#define MOTOR3_STEP_GPIO_TOGGLE() 		(MOTOR3_STEP_GPIO_NAME->PTOR=(1<<MOTOR3_STEP_REG))
#define MOTOR3_STEP_STATUS() 			(MOTOR3_STEP_GPIO_NAME->PDOR&(1<<MOTOR3_STEP_REG))

#define MOTORROT_STEP_TIMER_CHNL		5		// USR Config
#define MOTORROT_STEP_PORT				D		// USR Config
#define MOTORROT_STEP_REG				5		// USR Config
#define MOTORROT_STEP_PULL_ENABLE		(1) 	// USR Config		// 1 = Enable, 0 = Disable
#define MOTORROT_STEP_PULLUP			(0) 	// USR Config		// 1 = Pullup, 0 = Pulldown
#define MOTORROT_STEP_DSE				(1) 	// USR Config		// 1 = Drive Strength enable , 0 = off
#define MOTORROT_STEP_PORT_NAME 		PORT_MKR(MOTORROT_STEP_PORT)
#define MOTORROT_STEP_GPIO_NAME 		GPIO_MKR(MOTORROT_STEP_PORT)
#define MOTORROT_STEP_MUX_GPIO()     	(MOTORROT_STEP_PORT_NAME->PCR[MOTORROT_STEP_REG]= PORT_PCR_MUX(1)|PORT_PCR_PS(MOTORROT_STEP_PULLUP)|PORT_PCR_PE(MOTORROT_STEP_PULL_ENABLE)|PORT_PCR_DSE(MOTORROT_STEP_DSE))
#define MOTORROT_STEP_MUX_FTM()     	(MOTORROT_STEP_PORT_NAME->PCR[MOTORROT_STEP_REG]= PORT_PCR_MUX(3)|PORT_PCR_PS(MOTORROT_STEP_PULLUP)|PORT_PCR_PE(MOTORROT_STEP_PULL_ENABLE)|PORT_PCR_DSE(MOTORROT_STEP_DSE))
#define MOTORROT_STEP_SET_OUTPUT()  	(MOTORROT_STEP_GPIO_NAME->PDDR|=(1<<MOTORROT_STEP_REG))
#define MOTORROT_STEP_GPIO_LOW()  		(MOTORROT_STEP_GPIO_NAME->PCOR=(1<<MOTORROT_STEP_REG))
#define MOTORROT_STEP_GPIO_HIGH() 		(MOTORROT_STEP_GPIO_NAME->PSOR=(1<<MOTORROT_STEP_REG))
#define MOTORROT_STEP_GPIO_TOGGLE() 	(MOTORROT_STEP_GPIO_NAME->PTOR=(1<<MOTORROT_STEP_REG))
#define MOTORROT_STEP_STATUS() 			(MOTORROT_STEP_GPIO_NAME->PDOR&(1<<MOTORROT_STEP_REG))

#endif


#if ENABLE_DIR					// Achtung Alle GPIO Bezogen auf PortB (statisch)

#define MOTOR1_DIR_PORT					B		// USR Config
#define MOTOR1_DIR_REG					0		// USR Config
#define MOTOR1_DIR_PULL_ENABLE			(1) 	// USR Config		// 1 = Enable, 0 = Disable
#define MOTOR1_DIR_PULLUP				(0) 	// USR Config		// 1 = Pullup, 0 = Pulldown
#define MOTOR1_DIR_DSE					(1) 	// USR Config		// 1 = Drive Strength enable , 0 = off
#define MOTOR1_DIR_PORT_NAME 			PORT_MKR(MOTOR1_DIR_PORT)
#define MOTOR1_DIR_GPIO_NAME 			GPIO_MKR(MOTOR1_DIR_PORT)
#define MOTOR1_DIR_MUX_GPIO()     		(MOTOR1_DIR_PORT_NAME->PCR[MOTOR1_DIR_REG]= PORT_PCR_MUX(1)|PORT_PCR_PS(MOTOR1_DIR_PULLUP)|PORT_PCR_PE(MOTOR1_DIR_PULL_ENABLE)|PORT_PCR_DSE(MOTOR1_DIR_DSE))
#define MOTOR1_DIR_MUX_FTM()     		(MOTOR1_DIR_PORT_NAME->PCR[MOTOR1_DIR_REG]= PORT_PCR_MUX(3)|PORT_PCR_PS(MOTOR1_DIR_PULLUP)|PORT_PCR_PE(MOTOR1_DIR_PULL_ENABLE)|PORT_PCR_DSE(MOTOR1_DIR_DSE))
#define MOTOR1_DIR_SET_OUTPUT()  		(MOTOR1_DIR_GPIO_NAME->PDDR|=(1<<MOTOR1_DIR_REG))
#define MOTOR1_DIR_REV()     	        (GPIOB->PCOR=(1<<MOTOR1_DIR_REG))
#define MOTOR1_DIR_FWD()     	        (GPIOB->PSOR=(1<<MOTOR1_DIR_REG))
#define MOTOR1_DIR_GPIO_TOGGLE() 		(MOTOR1_DIR_GPIO_NAME->PTOR=(1<<MOTOR1_DIR_REG))
#define MOTOR1_DIR_STATUS() 			(MOTOR1_DIR_GPIO_NAME->PDOR&(1<<MOTOR1_DIR_REG))

#define MOTOR2_DIR_PORT					B		// USR Config
#define MOTOR2_DIR_REG					1		// USR Config
#define MOTOR2_DIR_PULL_ENABLE			(1) 	// USR Config		// 1 = Enable, 0 = Disable
#define MOTOR2_DIR_PULLUP				(0) 	// USR Config		// 1 = Pullup, 0 = Pulldown
#define MOTOR2_DIR_DSE					(1) 	// USR Config		// 1 = Drive Strength enable , 0 = off
#define MOTOR2_DIR_PORT_NAME 			PORT_MKR(MOTOR2_DIR_PORT)
#define MOTOR2_DIR_GPIO_NAME 			GPIO_MKR(MOTOR2_DIR_PORT)
#define MOTOR2_DIR_MUX_GPIO()     		(MOTOR2_DIR_PORT_NAME->PCR[MOTOR2_DIR_REG]= PORT_PCR_MUX(1)|PORT_PCR_PS(MOTOR2_DIR_PULLUP)|PORT_PCR_PE(MOTOR2_DIR_PULL_ENABLE)|PORT_PCR_DSE(MOTOR2_DIR_DSE))
#define MOTOR2_DIR_MUX_FTM()     		(MOTOR2_DIR_PORT_NAME->PCR[MOTOR2_DIR_REG]= PORT_PCR_MUX(3)|PORT_PCR_PS(MOTOR2_DIR_PULLUP)|PORT_PCR_PE(MOTOR2_DIR_PULL_ENABLE)|PORT_PCR_DSE(MOTOR2_DIR_DSE))
#define MOTOR2_DIR_SET_OUTPUT()  		(MOTOR2_DIR_GPIO_NAME->PDDR|=(1<<MOTOR2_DIR_REG))
#define MOTOR2_DIR_REV()     	        (GPIOB->PCOR=(1<<MOTOR2_DIR_REG))
#define MOTOR2_DIR_FWD()     	        (GPIOB->PSOR=(1<<MOTOR2_DIR_REG))
#define MOTOR2_DIR_GPIO_TOGGLE() 		(MOTOR2_DIR_GPIO_NAME->PTOR=(1<<MOTOR2_DIR_REG))
#define MOTOR2_DIR_STATUS() 			(MOTOR2_DIR_GPIO_NAME->PDOR&(1<<MOTOR2_DIR_REG))

#define MOTOR3_DIR_PORT					B		// USR Config
#define MOTOR3_DIR_REG					2		// USR Config
#define MOTOR3_DIR_PULL_ENABLE			(1) 	// USR Config		// 1 = Enable, 0 = Disable
#define MOTOR3_DIR_PULLUP				(0) 	// USR Config		// 1 = Pullup, 0 = Pulldown
#define MOTOR3_DIR_DSE					(1) 	// USR Config		// 1 = Drive Strength enable , 0 = off
#define MOTOR3_DIR_PORT_NAME 			PORT_MKR(MOTOR3_DIR_PORT)
#define MOTOR3_DIR_GPIO_NAME 			GPIO_MKR(MOTOR3_DIR_PORT)
#define MOTOR3_DIR_MUX_GPIO()     		(MOTOR3_DIR_PORT_NAME->PCR[MOTOR3_DIR_REG]= PORT_PCR_MUX(1)|PORT_PCR_PS(MOTOR3_DIR_PULLUP)|PORT_PCR_PE(MOTOR3_DIR_PULL_ENABLE)|PORT_PCR_DSE(MOTOR3_DIR_DSE))
#define MOTOR3_DIR_MUX_FTM()     		(MOTOR3_DIR_PORT_NAME->PCR[MOTOR3_DIR_REG]= PORT_PCR_MUX(3)|PORT_PCR_PS(MOTOR3_DIR_PULLUP)|PORT_PCR_PE(MOTOR3_DIR_PULL_ENABLE)|PORT_PCR_DSE(MOTOR3_DIR_DSE))
#define MOTOR3_DIR_SET_OUTPUT()  		(MOTOR3_DIR_GPIO_NAME->PDDR|=(1<<MOTOR3_DIR_REG))
#define MOTOR3_DIR_REV()     	        (GPIOB->PCOR=(1<<MOTOR3_DIR_REG))
#define MOTOR3_DIR_FWD()     	        (GPIOB->PSOR=(1<<MOTOR3_DIR_REG))
#define MOTOR3_DIR_GPIO_TOGGLE() 		(MOTOR3_DIR_GPIO_NAME->PTOR=(1<<MOTOR3_DIR_REG))
#define MOTOR3_DIR_STATUS() 			(MOTOR3_DIR_GPIO_NAME->PDOR&(1<<MOTOR3_DIR_REG))

#define MOTORROT_DIR_PORT				B		// USR Config
#define MOTORROT_DIR_REG				3		// USR Config
#define MOTORROT_DIR_PULL_ENABLE		(1) 	// USR Config		// 1 = Enable, 0 = Disable
#define MOTORROT_DIR_PULLUP				(0) 	// USR Config		// 1 = Pullup, 0 = Pulldown
#define MOTORROT_DIR_DSE				(1) 	// USR Config		// 1 = Drive Strength enable , 0 = off
#define MOTORROT_DIR_PORT_NAME 			PORT_MKR(MOTORROT_DIR_PORT)
#define MOTORROT_DIR_GPIO_NAME 			GPIO_MKR(MOTORROT_DIR_PORT)
#define MOTORROT_DIR_MUX_GPIO()     	(MOTORROT_DIR_PORT_NAME->PCR[MOTORROT_DIR_REG]= PORT_PCR_MUX(1)|PORT_PCR_PS(MOTORROT_DIR_PULLUP)|PORT_PCR_PE(MOTORROT_DIR_PULL_ENABLE)|PORT_PCR_DSE(MOTORROT_DIR_DSE))
#define MOTORROT_DIR_MUX_FTM()     		(MOTORROT_DIR_PORT_NAME->PCR[MOTORROT_DIR_REG]= PORT_PCR_MUX(3)|PORT_PCR_PS(MOTORROT_DIR_PULLUP)|PORT_PCR_PE(MOTORROT_DIR_PULL_ENABLE)|PORT_PCR_DSE(MOTORROT_DIR_DSE))
#define MOTORROT_DIR_SET_OUTPUT()  		(MOTORROT_DIR_GPIO_NAME->PDDR|=(1<<MOTORROT_DIR_REG))
#define MOTORROT_DIR_REV()     	        (GPIOB->PCOR=(1<<MOTORROT_DIR_REG))
#define MOTORROT_DIR_FWD()     	        (GPIOB->PSOR=(1<<MOTORROT_DIR_REG))
#define MOTORROT_DIR_GPIO_TOGGLE() 		(MOTORROT_DIR_GPIO_NAME->PTOR=(1<<MOTORROT_DIR_REG))
#define MOTORROT_DIR_STATUS() 			(MOTORROT_DIR_GPIO_NAME->PDOR&(1<<MOTORROT_DIR_REG))

#endif


#if ENABLE_EN

#define MOTOR1_EN_PORT					B		// USR Config
#define MOTOR1_EN_REG					16		// USR Config
#define MOTOR1_EN_PULL_ENABLE			(1) 	// USR Config		// 1 = Enable, 0 = Disable
#define MOTOR1_EN_PULLUP				(0) 	// USR Config		// 1 = Pullup, 0 = Pulldown
#define MOTOR1_EN_DSE					(1) 	// USR Config		// 1 = Drive Strength enable , 0 = off
#define MOTOR1_EN_PORT_NAME 			PORT_MKR(MOTOR1_EN_PORT)
#define MOTOR1_EN_GPIO_NAME 			GPIO_MKR(MOTOR1_EN_PORT)
#define MOTOR1_EN_MUX_GPIO()     		(MOTOR1_EN_PORT_NAME->PCR[MOTOR1_EN_REG]= PORT_PCR_MUX(1)|PORT_PCR_PS(MOTOR1_EN_PULLUP)|PORT_PCR_PE(MOTOR1_EN_PULL_ENABLE)|PORT_PCR_DSE(MOTOR1_EN_DSE))
#define MOTOR1_EN_MUX_FTM()     		(MOTOR1_EN_PORT_NAME->PCR[MOTOR1_EN_REG]= PORT_PCR_MUX(3)|PORT_PCR_PS(MOTOR1_EN_PULLUP)|PORT_PCR_PE(MOTOR1_EN_PULL_ENABLE)|PORT_PCR_DSE(MOTOR1_EN_DSE))
#define MOTOR1_EN_SET_OUTPUT()  		(MOTOR1_EN_GPIO_NAME->PDDR|=(1<<MOTOR1_EN_REG))
#define MOTOR1_EN_ENABLE()     	    	(GPIOB->PCOR=(1<<MOTOR1_EN_REG))
#define MOTOR1_EN_DISABLE()     	    (GPIOB->PSOR=(1<<MOTOR1_EN_REG))
#define MOTOR1_EN_GPIO_TOGGLE() 		(MOTOR1_EN_GPIO_NAME->PTOR=(1<<MOTOR1_EN_REG))
#define MOTOR1_EN_STATUS() 				(MOTOR1_EN_GPIO_NAME->PDOR&(1<<MOTOR1_EN_REG))

#define MOTOR2_EN_PORT					B		// USR Config
#define MOTOR2_EN_REG					17		// USR Config
#define MOTOR2_EN_PULL_ENABLE			(1) 	// USR Config		// 1 = Enable, 0 = Disable
#define MOTOR2_EN_PULLUP				(0) 	// USR Config		// 1 = Pullup, 0 = Pulldown
#define MOTOR2_EN_DSE					(1) 	// USR Config		// 1 = Drive Strength enable , 0 = off
#define MOTOR2_EN_PORT_NAME 			PORT_MKR(MOTOR2_EN_PORT)
#define MOTOR2_EN_GPIO_NAME 			GPIO_MKR(MOTOR2_EN_PORT)
#define MOTOR2_EN_MUX_GPIO()     		(MOTOR2_EN_PORT_NAME->PCR[MOTOR2_EN_REG]= PORT_PCR_MUX(1)|PORT_PCR_PS(MOTOR2_EN_PULLUP)|PORT_PCR_PE(MOTOR2_EN_PULL_ENABLE)|PORT_PCR_DSE(MOTOR2_EN_DSE))
#define MOTOR2_EN_MUX_FTM()     		(MOTOR2_EN_PORT_NAME->PCR[MOTOR2_EN_REG]= PORT_PCR_MUX(3)|PORT_PCR_PS(MOTOR2_EN_PULLUP)|PORT_PCR_PE(MOTOR2_EN_PULL_ENABLE)|PORT_PCR_DSE(MOTOR2_EN_DSE))
#define MOTOR2_EN_SET_OUTPUT()  		(MOTOR2_EN_GPIO_NAME->PDDR|=(1<<MOTOR2_EN_REG))
#define MOTOR2_EN_ENABLE()     	    	(GPIOB->PCOR=(1<<MOTOR2_EN_REG))
#define MOTOR2_EN_DISABLE()     	    (GPIOB->PSOR=(1<<MOTOR2_EN_REG))
#define MOTOR2_EN_GPIO_TOGGLE() 		(MOTOR2_EN_GPIO_NAME->PTOR=(1<<MOTOR2_EN_REG))
#define MOTOR2_EN_STATUS() 				(MOTOR2_EN_GPIO_NAME->PDOR&(1<<MOTOR2_EN_REG))

#define MOTOR3_EN_PORT					B		// USR Config
#define MOTOR3_EN_REG					18		// USR Config
#define MOTOR3_EN_PULL_ENABLE			(1) 	// USR Config		// 1 = Enable, 0 = Disable
#define MOTOR3_EN_PULLUP				(0) 	// USR Config		// 1 = Pullup, 0 = Pulldown
#define MOTOR3_EN_DSE					(1) 	// USR Config		// 1 = Drive Strength enable , 0 = off
#define MOTOR3_EN_PORT_NAME 			PORT_MKR(MOTOR3_EN_PORT)
#define MOTOR3_EN_GPIO_NAME 			GPIO_MKR(MOTOR3_EN_PORT)
#define MOTOR3_EN_MUX_GPIO()     		(MOTOR3_EN_PORT_NAME->PCR[MOTOR3_EN_REG]= PORT_PCR_MUX(1)|PORT_PCR_PS(MOTOR3_EN_PULLUP)|PORT_PCR_PE(MOTOR3_EN_PULL_ENABLE)|PORT_PCR_DSE(MOTOR3_EN_DSE))
#define MOTOR3_EN_MUX_FTM()     		(MOTOR3_EN_PORT_NAME->PCR[MOTOR3_EN_REG]= PORT_PCR_MUX(3)|PORT_PCR_PS(MOTOR3_EN_PULLUP)|PORT_PCR_PE(MOTOR3_EN_PULL_ENABLE)|PORT_PCR_DSE(MOTOR3_EN_DSE))
#define MOTOR3_EN_SET_OUTPUT()  		(MOTOR3_EN_GPIO_NAME->PDDR|=(1<<MOTOR3_EN_REG))
#define MOTOR3_EN_ENABLE()     	    	(GPIOB->PCOR=(1<<MOTOR3_EN_REG))
#define MOTOR3_EN_DISABLE()     	    (GPIOB->PSOR=(1<<MOTOR3_EN_REG))
#define MOTOR3_EN_GPIO_TOGGLE() 		(MOTOR3_EN_GPIO_NAME->PTOR=(1<<MOTOR3_EN_REG))
#define MOTOR3_EN_STATUS() 				(MOTOR3_EN_GPIO_NAME->PDOR&(1<<MOTOR3_EN_REG))

#define MOTORROT_EN_PORT				B		// USR Config
#define MOTORROT_EN_REG					19		// USR Config
#define MOTORROT_EN_PULL_ENABLE			(1) 	// USR Config		// 1 = Enable, 0 = Disable
#define MOTORROT_EN_PULLUP				(0) 	// USR Config		// 1 = Pullup, 0 = Pulldown
#define MOTORROT_EN_DSE					(1) 	// USR Config		// 1 = Drive Strength enable , 0 = off
#define MOTORROT_EN_PORT_NAME 			PORT_MKR(MOTORROT_EN_PORT)
#define MOTORROT_EN_GPIO_NAME 			GPIO_MKR(MOTORROT_EN_PORT)
#define MOTORROT_EN_MUX_GPIO()     		(MOTORROT_EN_PORT_NAME->PCR[MOTORROT_EN_REG]= PORT_PCR_MUX(1)|PORT_PCR_PS(MOTORROT_EN_PULLUP)|PORT_PCR_PE(MOTORROT_EN_PULL_ENABLE)|PORT_PCR_DSE(MOTORROT_EN_DSE))
#define MOTORROT_EN_MUX_FTM()     		(MOTORROT_EN_PORT_NAME->PCR[MOTORROT_EN_REG]= PORT_PCR_MUX(3)|PORT_PCR_PS(MOTORROT_EN_PULLUP)|PORT_PCR_PE(MOTORROT_EN_PULL_ENABLE)|PORT_PCR_DSE(MOTORROT_EN_DSE))
#define MOTORROT_EN_SET_OUTPUT()  		(MOTORROT_EN_GPIO_NAME->PDDR|=(1<<MOTORROT_EN_REG))
#define MOTORROT_EN_ENABLE()     	    (GPIOB->PCOR=(1<<MOTORROT_EN_REG))
#define MOTORROT_EN_DISABLE()     	    (GPIOB->PSOR=(1<<MOTORROT_EN_REG))
#define MOTORROT_EN_GPIO_TOGGLE() 		(MOTORROT_EN_GPIO_NAME->PTOR=(1<<MOTORROT_EN_REG))
#define MOTORROT_EN_STATUS() 			(MOTORROT_EN_GPIO_NAME->PDOR&(1<<MOTORROT_EN_REG))

#endif


#endif /* MOTOR_STEPPER_CONFIG_H_ */
