/*
 * stepper_config.h
 *
 *  Created on: 06.03.2026
 *      Author: roman
 */

#ifndef MOTOR_STEPPER_CONFIG_H_
#define MOTOR_STEPPER_CONFIG_H_

#define ENABLE_STEP		1
#define ENABLE_DIR		0
#define ENABLE_EN		0
#define ENABLE_ROT		0


#if ENABLE_STEP
#define MOTOR1_TIMER_CHAN		1
#define MOTOR1_STEP      		(PORTA->PCR[4])
#define MOTOR1_STEP_GPIO()     	(MOTOR1_STEP = PORT_PCR_MUX(1)|PORT_PCR_PS(0)|PORT_PCR_PE(0)|PORT_PCR_DSE(1))
#define MOTOR1_STEP_GPIO_LOW()  (GPIOA->PCOR=(1<<4))
#define MOTOR1_STEP_FTM()      	(MOTOR1_STEP = PORT_PCR_MUX(3)|PORT_PCR_PS(0)|PORT_PCR_PE(0)|PORT_PCR_DSE(1))
#define MOTOR2_TIMER_CHAN		2
#define MOTOR2_STEP      		(PORTA->PCR[5])
#define MOTOR2_STEP_GPIO()     	(MOTOR2_STEP = PORT_PCR_MUX(1)|PORT_PCR_PS(1)|PORT_PCR_PE(1)|PORT_PCR_DSE(1))
#define MOTOR2_STEP_GPIO_LOW()  (GPIOA->PCOR=(1<<5))
#define MOTOR2_STEP_FTM()      	(MOTOR2_STEP = PORT_PCR_MUX(3)|PORT_PCR_PS(1)|PORT_PCR_PE(1)|PORT_PCR_DSE(1))
#define MOTOR3_TIMER_CHAN		4
#define MOTOR3_STEP      		(PORTD->PCR[4])
#define MOTOR3_STEP_GPIO()     	(MOTOR3_STEP = PORT_PCR_MUX(1)|PORT_PCR_PS(1)|PORT_PCR_PE(1)|PORT_PCR_DSE(1))
#define MOTOR3_STEP_FTM()      	(MOTOR3_STEP = PORT_PCR_MUX(4)|PORT_PCR_PS(1)|PORT_PCR_PE(1)|PORT_PCR_DSE(1))
#define MOTORROT_TIMER_CHAN		5
#define MOTOROT_STEP      		(PORTD->PCR[5])
#define MOTORROT_STEP_GPIO()    (MOTOROT_STEP = PORT_PCR_MUX(1)|PORT_PCR_PS(1)|PORT_PCR_PE(1)|PORT_PCR_DSE(1))
#define MOTORROT_STEP_FTM()     (MOTOROT_STEP |= PORT_PCR_MUX(4))
#endif

#if ENABLE_DIR
#define MOTOR1_DIR      		(PORTA->PCR[4])
#define MOTOR1_DIR_GPIO()     	(MOTOR1_DIR = PORT_PCR_MUX(1))
#define MOTOR1_DIR_FWD()     	(MOTOR1_DIR = PORT_PCR_MUX(1))
#define MOTOR1_DIR_REV()     	(MOTOR1_DIR = PORT_PCR_MUX(1))
#define MOTOR2_DIR      		(PORTA->PCR[5])
#define MOTOR2_DIR_GPIO()     	(MOTOR2_DIR = PORT_PCR_MUX(1))
#define MOTOR2_DIR_FWD()     	(MOTOR2_DIR = PORT_PCR_MUX(1))
#define MOTOR2_DIR_REV()     	(MOTOR2_DIR = PORT_PCR_MUX(1))
#define MOTOR3_DIR      		(PORTD->PCR[4])
#define MOTOR3_DIR_GPIO()     	(MOTOR3_DIR = PORT_PCR_MUX(1))
#define MOTOR3_DIR_FWD()     	(MOTOR3_DIR = PORT_PCR_MUX(1))
#define MOTOR3_DIR_REV()     	(MOTOR3_DIR = PORT_PCR_MUX(1))
#define MOTORROT_DIR      		(PORTD->PCR[5])
#define MOTORROT_DIR_GPIO()     (MOTORROT_DIR = PORT_PCR_MUX(1))
#define MOTORROT_DIR_FWD()     (MOTORROT_DIR = PORT_PCR_MUX(1))
#define MOTORROT_DIR_REV()     (MOTORROT_DIR = PORT_PCR_MUX(1))
#endif


#if ENABLE_EN
#define MOTOR1_EN      			(PORTA->PCR[4])
#define MOTOR1_EN_GPIO()     	(MOTOR1_EN = PORT_PCR_MUX(1))
#define MOTOR2_EN      			(PORTA->PCR[4])
#define MOTOR2_EN_GPIO()     	(MOTOR2_EN = PORT_PCR_MUX(1))
#define MOTOR3_EN      			(PORTA->PCR[4])
#define MOTOR3_EN_GPIO()     	(MOTOR3_EN = PORT_PCR_MUX(1))
#define MOTORROT_EN      		(PORTA->PCR[4])
#define MOTORROT_EN_GPIO()     	(MOTORROT_EN = PORT_PCR_MUX(1))
#endif

#endif /* MOTOR_STEPPER_CONFIG_H_ */
